name: InvBroadcast
version: '${project.version}'
main: ru.invstudio.invbroadcast.InvBroadcast
api-version: '1.16'
authors: [invstudio]
website: t.me/invstudio
commands:
  broadcast:
    aliases:
      - bc
  invbc: